version: '3.4'

services:

  unleash-server:
    volumes:
      - ../scripts:/scripts
    ports:
      - "4242:4242"
    expose:
      - "4242"
    environment:
      DATABASE_URL: "postgres://postgres:unleash@postgresdata/unleash"
      DATABASE_SSL: "false"
      LOG_LEVEL: "warn"
      INIT_ADMIN_API_TOKENS: ${INIT_ADMIN_API_TOKENS}
      INIT_FRONTEND_API_TOKENS: ${INIT_FRONTEND_API_TOKENS}
      INIT_CLIENT_API_TOKENS: ${INIT_CLIENT_API_TOKENS}

  unleash-init:
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # create example feature toggle
      curl -i -X POST http://unleash-server:4242/api/admin/projects/default/features \\
        -H 'Authorization: ${INIT_ADMIN_API_TOKENS}' \\
        -H 'Content-Type: application/json' \\
        --data-raw '{ \"name\": \"ExampleFeature\" }'

      # create standard rollout strategy
      curl -i -X POST http://unleash-server:4242/api/admin/projects/default/features/ExampleFeature/environments/development/strategies \\
        -H 'Authorization: ${INIT_ADMIN_API_TOKENS}' \\
        -H 'Content-Type: application/json' \\
        --data-raw '{ \"name\": \"default\", \"constraints\": [], \"parameters\": {} }'

      # enable example feature toggle
      curl -i -X POST http://unleash-server:4242/api/admin/projects/default/features/ExampleFeature/environments/development/on \\
        -H 'Authorization: ${INIT_ADMIN_API_TOKENS}' \\
        -H 'Content-Type: application/json'
      "

  postgresdata:
    environment:
      POSTGRES_DB: "unleash"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    expose:
      - "5432"

  unleash-example-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - UNLEASH_API_TOKEN=${UNLEASH_API_TOKEN}
    ports:
      - "8000:80"
    expose:
      - "80"
