version: '3.4'

services:

  unleash-server:
    volumes:
      - ../scripts:/scripts
    ports:
      - "4242:4242"
    expose:
      - "4242"
    environment:
      DATABASE_URL: "postgres://postgres:unleash@postgresdata/unleash"
      DATABASE_SSL: "false"
      LOG_LEVEL: "warn"
      INIT_FRONTEND_API_TOKENS: "default:development.unleash-insecure-frontend-api-token"
      INIT_CLIENT_API_TOKENS: "default:development.unleash-insecure-api-token"

  postgresdata:
    environment:
      POSTGRES_DB: "unleash"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    expose:
      - "5432"

  unleash-example-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - UNLEASH_API_TOKEN=${UNLEASH_API_TOKEN}
    ports:
      - "8000:80"
    expose:
      - "80"
