version: '3.4'

networks:
  unleash:

services:

  unleash-server:
    image: unleashorg/unleash-server:latest
    container_name: unleash-server
    depends_on:
      postgresdata:
        condition: service_healthy
    networks:
      unleash:
    command: ["/scripts/wait-for", "postgresdata:5432", "--", "node", "index.js"]
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s

  unleash-init:
    image: curlimages/curl:latest
    container_name: unleash-init
    depends_on:
      unleash-server:
        condition: service_healthy
    networks:
      unleash:

  postgresdata:
    image: postgres:latest
    container_name: postgresdata
    networks:
      unleash:
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres", "--host=127.0.0.1", "--port=5432"]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s

  unleash-example-api:
    image: ${DOCKER_REGISTRY-}unleash-example-api
    container_name: unleash-example-api
    networks:
      unleash:
    depends_on:
      unleash-server:
        condition: service_healthy
    build:
      context: .
      dockerfile: Services/UnleashExample/UnleashExample.API/Dockerfile
